[[metadata.heroku]]
  root-package = "github.com/signavio/workflow-connector"
  go-version = "1.9.4"
  install = [ "./..." ]
  
[[constraint]]
  name = "github.com/DATA-DOG/go-sqlmock"
  version = "1.3.0"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  branch = "master"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "1"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1"

[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"

[[constraint]]
  name = "github.com/urfave/negroni"
  version = "0.2.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1"
