# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
      - image: circleci/mysql:5.7-ram
        environment:
          MYSQL_DATABASE: circle_test
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_HOST: "%"
          MYSQL_USER: root
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
    working_directory: ~/github.com/signavio/workflow-connector

    steps:
      - checkout
      - run:
          name: Run tests using a mock database
          command: go test -v ./...
      - run:
          name: Resolve mysql prerequisites
          command: |
            sudo apt-get update
            sudo apt-get install mysql-client
      - run:
          name: Migrate coffee example to mysql database
          environment:
            MYSQL_DATABASE: circle_test
            MYSQL_HOST: 127.0.0.1
            MYSQL_ROOT_HOST: "%"
            MYSQL_USER: root
          command: build/migrate-to-mysql.sh
      - run:
          name: Run tests on a mysql database
          environment:
            MYSQL_DATABASE_URL: "root:@tcp(localhost:3306)/circle_test?parseTime=true"
          command: go test -v ./... -args -db mysql
