# Using a SQLite database
---
port: 8080
database:
  driver: sqlite3
  url: test.db 
tls:
  enabled: false
  publicKey: ./config/server.crt
  privateKey: ./config/server.key
auth:
  username: wfauser
  # password = Foobar
  passwordHash: "$argon2i$v=19$m=512,t=2,p=2$SUxvdmVTYWx0Q2FrZXMhISE$UgSWnBB5OkdqMAu+OfvwNLVMUijMnnmVm0kRSfmS9E8"
logging: true
...
# Using a Microsoft SQL Server database
---
port: 8080
database:
  driver: sqlserver
  url: sqlserver://john:84mj29rSgHz@172.17.8.2?database=test
tls:
  enabled: false
  publicKey: ./config/server.crt
  privateKey: ./config/server.key
auth:
  username: wfauser
  # password = Foobar
  passwordHash: "$argon2i$v=19$m=512,t=2,p=2$SUxvdmVTYWx0Q2FrZXMhISE$UgSWnBB5OkdqMAu+OfvwNLVMUijMnnmVm0kRSfmS9E8"
logging: true
...
# Using a Postgres database
---
port: 8080
database:
  driver: postgres
  url: postgres://bob:l120arSgHz@172.17.8.2/test?sslmode=verify-full
tls:
  enabled: false
  publicKey: ./config/server.crt
  privateKey: ./config/server.key
auth:
  username: wfauser
  # password = Foobar
  passwordHash: "$argon2i$v=19$m=512,t=2,p=2$SUxvdmVTYWx0Q2FrZXMhISE$UgSWnBB5OkdqMAu+OfvwNLVMUijMnnmVm0kRSfmS9E8"
logging: true
...
# Using a mysql database
---
port: 8080
database:
  driver: mysql
  # url = username:password@protocol(address)/dbname?param=value
  url: bob:l120arSgHz@tcp(172.17.8.2:3306)/test?timeout=90s&collation=utf8mb4_unicode_ci
tls:
  enabled: false
  publicKey: ./config/server.crt
  privateKey: ./config/server.key
auth:
  username: wfauser
  # password = Foobar
  passwordHash: "$argon2i$v=19$m=512,t=2,p=2$SUxvdmVTYWx0Q2FrZXMhISE$UgSWnBB5OkdqMAu+OfvwNLVMUijMnnmVm0kRSfmS9E8"
logging: true
...
